Add support for LLVM 14
staticafi/sbt-instrumentation pull request #67
Opened 2022-05-03 19:31 UTC by lzaoral

2022-05-03 21:30 UTC, mchalupa requested changes

2022-05-03 21:30 UTC, mchalupa commented on src/instr.cpp
> +    Type* Ty = GV->getValueType();;
Typo: two semi-colons.

2022-05-03 21:35 UTC, lzaoral commented on src/instr.cpp
> +    Type* Ty = GV->getValueType();;
Thanks! Addressed in e69e7f7.

2022-05-09 12:30 UTC, mchalupa approved these changes
LGTM.

2022-05-16 14:07 UTC, merged